# Generated by Django 2.2.16 on 2023-01-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_auto_20230116_1819"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(
                help_text="Укажите ключ адреса страницы группы",
                unique=True,
                verbose_name="Идентификатор",
            ),
        ),
    ]
